site_name: unittest-learning
repo_url: https://github.com/ChargeStorm/unittest-learning
theme:
  name: material
  logo: assets/dark_logo.png
  features:
    - content.code.copy
    - navigation.expand
    - navigation.sections
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    - scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - autorefs
  - mkdocstrings:
      custom_templates: templates
      handlers:
        python:
          options:
            docstring_style: google
            merge_init_into_class: true
            show_source: true
            members_order: source
            show_root_heading: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Before Starting:
      - Test Structure Methodology: test-structure-methodology.md
      - Package Specific Test Libraries: package-specific-test-libraries.md
      - Code Coverage: code-coverage.md
      - Pytest Plugins: pytest-plugins.md
      - Pytest CLI: pytest-cli.md
  - Code Examples:
      - Assertion: assertion.md
      - Mocking: mocking.md
      - Fixtures: fixtures.md
      - Parametrization: parametrization.md
      - Markers: markers.md
      - Exceptions: exceptions.md
      - Capturing Output: capturing-output.md
      - Logging: logging.md

watch:
  - tests/
