trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  docs-name: "unittest-learning"
  docs-version: "main"

resources:
  repositories:
    - repository: pipeline-utilities
      type: git
      name: ctek/pipeline-utilities
      ref: refs/tags/2.6.0
jobs:
  - job: "docs"
    displayName: "Build docs and upload to docshost"
    steps:
      - checkout: self

      - bash: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install uv"

      - bash: |
          uv run --all-groups mkdocs build
        displayName: "Mkdocs build"

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "site"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(docs-name)-$(docs-version).zip"
          replaceExistingArchive: true
        displayName: "Create docs zip"

      - template: templates/docshost/publish-docs-step.yml@pipeline-utilities
        parameters:
          artifact: "$(docs-name)-$(docs-version).zip"
          uniqueKey: $(DOCSHOST_UNIQUE_KEY)
          reupload: true
          pipelineArtifact: "" # Note: If pipelineArtifact is set to empty, it will skip the download step and use the artifact from the current job.
